"""Printable patient summary generation."""

import json

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse

from .audit import log_action
from .auth import require_medical_role
from .database import query

router = APIRouter(prefix="/api/patients/{patient_id}/summary", tags=["summary"])


@router.get("", response_class=HTMLResponse)
def get_patient_summary(patient_id: int, user: str = Depends(require_medical_role)) -> str:
    patients = query("SELECT * FROM patients WHERE id = ?", (patient_id,))
    if not patients:
        raise HTTPException(status_code=404, detail="Patient not found")
    p = patients[0]
    allergies = json.loads(p.get("allergies", "[]"))
    conditions = json.loads(p.get("chronic_conditions", "[]"))

    visits = query(
        "SELECT * FROM visits WHERE patient_id = ? ORDER BY visit_date DESC LIMIT 5",
        (patient_id,),
    )
    vitals = query(
        "SELECT * FROM vitals WHERE patient_id = ? ORDER BY recorded_at DESC LIMIT 1",
        (patient_id,),
    )
    vaccinations = query(
        "SELECT * FROM vaccinations WHERE patient_id = ? ORDER BY date_administered DESC",
        (patient_id,),
    )
    wounds = query(
        "SELECT * FROM wounds WHERE patient_id = ? AND status = 'open' ORDER BY created_at DESC",
        (patient_id,),
    )

    log_action(user, "read", "summary", str(patient_id))

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Patient Summary - {p['first_name']} {p['last_name']}</title>
<style>
body {{ font-family: serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
h1 {{ border-bottom: 2px solid #000; padding-bottom: 5px; }}
h2 {{ border-bottom: 1px solid #666; margin-top: 20px; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
th, td {{ border: 1px solid #999; padding: 5px 8px; text-align: left; }}
th {{ background: #eee; }}
.header {{ display: flex; justify-content: space-between; }}
.alert {{ color: red; font-weight: bold; }}
@media print {{ body {{ font-size: 11pt; }} }}
</style></head><body>
<h1>SURVIVE OS - Patient Summary</h1>
<div class="header">
<div><strong>Name:</strong> {p['first_name']} {p['last_name']}</div>
<div><strong>Patient ID:</strong> {p['patient_id']}</div>
</div>
<p><strong>DOB:</strong> {p['date_of_birth']} | <strong>Sex:</strong> {p['sex']} | <strong>Blood Type:</strong> {p.get('blood_type', 'N/A')}</p>
<p><strong>Emergency Contact:</strong> {p.get('emergency_contact', 'N/A')}</p>

<h2>Allergies</h2>
<p>{'<span class="alert">' + ', '.join(allergies) + '</span>' if allergies else 'None known'}</p>

<h2>Chronic Conditions</h2>
<p>{', '.join(conditions) if conditions else 'None'}</p>
"""

    if vitals:
        v = vitals[0]
        html += """<h2>Latest Vitals</h2>
<table><tr><th>Temp</th><th>Pulse</th><th>BP</th><th>Resp</th><th>SpO2</th><th>Weight</th><th>Recorded</th></tr>"""
        html += f"""<tr><td>{v.get('temperature', '-')}</td><td>{v.get('pulse', '-')}</td>
<td>{v.get('bp_systolic', '-')}/{v.get('bp_diastolic', '-')}</td>
<td>{v.get('respiration_rate', '-')}</td><td>{v.get('spo2', '-')}</td>
<td>{v.get('weight', '-')}</td><td>{v.get('recorded_at', '-')}</td></tr></table>"""

    if visits:
        html += "<h2>Recent Visits</h2><table><tr><th>Date</th><th>Provider</th><th>Assessment</th><th>Plan</th></tr>"
        for vis in visits:
            html += f"<tr><td>{vis['visit_date']}</td><td>{vis['provider']}</td><td>{vis.get('assessment', '')}</td><td>{vis.get('plan', '')}</td></tr>"
        html += "</table>"

    if vaccinations:
        html += "<h2>Vaccinations</h2><table><tr><th>Vaccine</th><th>Date</th><th>Administered By</th><th>Next Due</th></tr>"
        for vax in vaccinations:
            html += f"<tr><td>{vax['vaccine_name']}</td><td>{vax['date_administered']}</td><td>{vax.get('administered_by', '')}</td><td>{vax.get('next_dose_due', 'N/A')}</td></tr>"
        html += "</table>"

    if wounds:
        html += "<h2>Open Wounds</h2><table><tr><th>Location</th><th>Type</th><th>Size</th><th>Since</th></tr>"
        for w in wounds:
            html += f"<tr><td>{w['body_location']}</td><td>{w['wound_type']}</td><td>{w.get('size', '')}</td><td>{w['created_at']}</td></tr>"
        html += "</table>"

    if p.get("notes"):
        html += f"<h2>Notes</h2><p>{p['notes']}</p>"

    html += f"""<hr><p style="font-size:0.8em;">Generated by SURVIVE OS EHR-Lite | Patient ID: {p['patient_id']}</p>
</body></html>"""
    return html
