"""Dental reference data: tooth numbering and emergency protocols."""

ADULT_TOOTH_MAP = {
    1: "Upper right third molar",
    2: "Upper right second molar",
    3: "Upper right first molar",
    4: "Upper right second premolar",
    5: "Upper right first premolar",
    6: "Upper right canine",
    7: "Upper right lateral incisor",
    8: "Upper right central incisor",
    9: "Upper left central incisor",
    10: "Upper left lateral incisor",
    11: "Upper left canine",
    12: "Upper left first premolar",
    13: "Upper left second premolar",
    14: "Upper left first molar",
    15: "Upper left second molar",
    16: "Upper left third molar",
    17: "Lower left third molar",
    18: "Lower left second molar",
    19: "Lower left first molar",
    20: "Lower left second premolar",
    21: "Lower left first premolar",
    22: "Lower left canine",
    23: "Lower left lateral incisor",
    24: "Lower left central incisor",
    25: "Lower right central incisor",
    26: "Lower right lateral incisor",
    27: "Lower right canine",
    28: "Lower right first premolar",
    29: "Lower right second premolar",
    30: "Lower right first molar",
    31: "Lower right second molar",
    32: "Lower right third molar",
}

PEDIATRIC_TOOTH_MAP = {
    1: "Upper right second molar (A)",
    2: "Upper right first molar (B)",
    3: "Upper right canine (C)",
    4: "Upper right lateral incisor (D)",
    5: "Upper right central incisor (E)",
    6: "Upper left central incisor (F)",
    7: "Upper left lateral incisor (G)",
    8: "Upper left canine (H)",
    9: "Upper left first molar (I)",
    10: "Upper left second molar (J)",
    11: "Lower left second molar (K)",
    12: "Lower left first molar (L)",
    13: "Lower left canine (M)",
    14: "Lower left lateral incisor (N)",
    15: "Lower left central incisor (O)",
    16: "Lower right central incisor (P)",
    17: "Lower right lateral incisor (Q)",
    18: "Lower right canine (R)",
    19: "Lower right first molar (S)",
    20: "Lower right second molar (T)",
}
