"""Pre-seed chemistry recipes for the engineering module."""

import json

from app.database import execute


def seed_recipes() -> None:
    recipes = [
        {
            "name": "Basic Lye Soap",
            "category": "cleaning",
            "ingredients": [
                {"name": "lye (sodium hydroxide)", "quantity": "4.5 oz"},
                {"name": "water (distilled)", "quantity": "12 oz"},
                {"name": "olive oil or rendered tallow", "quantity": "32 oz"},
            ],
            "procedure": [
                "Slowly add lye to cold water in a heat-safe container (never add water to lye).",
                "Stir until lye is fully dissolved. Allow to cool to 100-110F.",
                "Heat oils/fats to 100-110F.",
                "Slowly pour lye solution into oils while stirring continuously.",
                "Stir or blend until mixture reaches 'trace' (thickens like pudding).",
                "Pour into molds and cover with towel.",
                "Allow to cure for 4-6 weeks before use.",
            ],
            "safety_notes": "Lye is extremely caustic. Wear gloves and eye protection. Work in ventilated area. Keep vinegar nearby to neutralize spills.",
            "yield": "Approximately 8-10 bars of soap",
            "difficulty": "medium",
        },
        {
            "name": "Charcoal Production",
            "category": "fuel",
            "ingredients": [
                {"name": "hardwood (oak, hickory, maple)", "quantity": "large supply"},
                {"name": "metal drum or earth pit", "quantity": "1"},
            ],
            "procedure": [
                "Cut hardwood into uniform pieces 3-4 inches in diameter.",
                "Load wood tightly into metal drum or dig a pit 3ft deep.",
                "Start a small fire on top and allow it to burn down.",
                "Seal the container/pit to restrict oxygen, leaving small vent hole.",
                "Allow to smolder for 6-12 hours until smoke turns from white to thin blue.",
                "Seal completely and allow to cool for 24 hours.",
                "Remove charcoal - it should be black, light, and break with a metallic ring.",
            ],
            "safety_notes": "Fire hazard. Perform outdoors in clear area. Carbon monoxide risk - never do indoors. Keep water/sand nearby.",
            "yield": "Approximately 25% of original wood weight",
            "difficulty": "medium",
        },
        {
            "name": "Biodiesel",
            "category": "fuel",
            "ingredients": [
                {"name": "vegetable oil (new or waste)", "quantity": "1 liter"},
                {"name": "methanol", "quantity": "200 ml"},
                {"name": "lye (sodium hydroxide)", "quantity": "3.5 g"},
            ],
            "procedure": [
                "Filter waste oil to remove food particles. Heat to 120F to remove water.",
                "Dissolve lye in methanol to create sodium methoxide (do in ventilated area).",
                "Heat oil to 130F in a non-aluminum container.",
                "Slowly add sodium methoxide to warm oil while stirring vigorously.",
                "Stir continuously for 1 hour.",
                "Allow mixture to settle for 8+ hours. Glycerin will sink to bottom.",
                "Drain glycerin from bottom. Wash biodiesel with water 3 times.",
                "Allow washed biodiesel to dry before use.",
            ],
            "safety_notes": "Methanol is toxic and flammable. Lye is caustic. Work outdoors with full PPE. No open flames near methanol.",
            "yield": "Approximately 1 liter of biodiesel",
            "difficulty": "hard",
        },
        {
            "name": "Salt Preservation (Dry Curing)",
            "category": "food_preservation",
            "ingredients": [
                {"name": "coarse salt (non-iodized)", "quantity": "1 lb per 5 lbs meat"},
                {"name": "meat or fish", "quantity": "as needed"},
                {"name": "sugar (optional)", "quantity": "small amount"},
                {"name": "herbs/spices (optional)", "quantity": "to taste"},
            ],
            "procedure": [
                "Trim meat and remove excess moisture with clean cloth.",
                "Mix salt with optional sugar and spices.",
                "Coat meat thoroughly with salt mixture, packing into all crevices.",
                "Place in non-reactive container (ceramic, glass, or food-grade plastic).",
                "Store in cool location (36-40F ideal) for 7 days per inch of thickness.",
                "After curing, rinse excess salt and pat dry.",
                "Hang in cool, dry, ventilated area to air dry if desired.",
            ],
            "safety_notes": "Use clean equipment. Maintain cool temperatures. Discard if meat develops off odors or green/black mold.",
            "yield": "Preserved meat that lasts months when stored properly",
            "difficulty": "easy",
        },
        {
            "name": "Smoke Preservation",
            "category": "food_preservation",
            "ingredients": [
                {"name": "meat or fish (pre-salted)", "quantity": "as needed"},
                {"name": "hardwood chips (hickory, apple, oak)", "quantity": "several pounds"},
            ],
            "procedure": [
                "Pre-cure meat with salt for at least 24 hours.",
                "Build or use a smokehouse - ensure meat hangs 4+ feet above fire.",
                "Start a small hardwood fire and let it burn to coals.",
                "Add damp wood chips to produce dense smoke.",
                "Cold smoke at 70-90F for 12-24 hours for preservation.",
                "Hot smoke at 120-180F for 4-8 hours for cooked and preserved product.",
                "Maintain consistent smoke. Do not let fire flame up.",
                "Meat is done when firm to touch and dark mahogany color.",
            ],
            "safety_notes": "Never use softwoods (pine, cedar) - they contain toxic resins. Maintain proper temperatures. Pre-salt meat before smoking.",
            "yield": "Smoked meat lasting weeks to months",
            "difficulty": "medium",
        },
        {
            "name": "Vinegar Pickling",
            "category": "food_preservation",
            "ingredients": [
                {"name": "white vinegar (5% acidity)", "quantity": "1 quart"},
                {"name": "water", "quantity": "1 quart"},
                {"name": "salt", "quantity": "2 tablespoons"},
                {"name": "vegetables (cucumbers, peppers, etc.)", "quantity": "2-3 lbs"},
                {"name": "garlic, dill, peppercorns", "quantity": "to taste"},
            ],
            "procedure": [
                "Wash and cut vegetables to desired size.",
                "Sterilize jars by boiling for 10 minutes.",
                "Pack vegetables tightly into hot jars with herbs and spices.",
                "Bring vinegar, water, and salt to a boil.",
                "Pour hot brine over vegetables, leaving 1/2 inch headspace.",
                "Remove air bubbles with clean utensil.",
                "Seal jars and process in boiling water bath for 10 minutes.",
                "Allow to cool and check seals. Store in cool, dark place.",
            ],
            "safety_notes": "Use tested recipes with proper acidity. Never reduce vinegar amount. Process in water bath for long-term storage.",
            "yield": "4-6 pint jars",
            "difficulty": "easy",
        },
        {
            "name": "Hide Glue (Wood Adhesive)",
            "category": "adhesive",
            "ingredients": [
                {"name": "rawhide scraps or sinew", "quantity": "1 lb"},
                {"name": "water", "quantity": "enough to cover"},
            ],
            "procedure": [
                "Cut rawhide into small pieces.",
                "Soak in water for 12-24 hours until soft.",
                "Place soaked hide and water in pot.",
                "Heat gently (do not boil) for several hours until hide dissolves into thick liquid.",
                "Strain through cloth to remove solids.",
                "Use warm - glue gels when cool.",
                "Can be stored dried and reconstituted with warm water.",
            ],
            "safety_notes": "Unpleasant odor during production. Work in ventilated area. Do not ingest.",
            "yield": "Approximately 1 cup of liquid glue",
            "difficulty": "easy",
        },
        {
            "name": "Water Purification (Solar Disinfection)",
            "category": "water_treatment",
            "ingredients": [
                {"name": "clear plastic or glass bottles (2L max)", "quantity": "as needed"},
                {"name": "water (pre-filtered if turbid)", "quantity": "as needed"},
            ],
            "procedure": [
                "Pre-filter water through cloth if turbid (must be relatively clear).",
                "Fill clean PET bottles 3/4 full.",
                "Shake vigorously for 20 seconds to oxygenate.",
                "Fill completely and cap tightly.",
                "Place on reflective surface (corrugated metal) in direct sunlight.",
                "Expose for minimum 6 hours in full sun, or 2 days if cloudy.",
                "Water is now safe to drink.",
            ],
            "safety_notes": "Does not remove chemical contaminants. Only use clear bottles. Not effective with very turbid water - filter first.",
            "yield": "Purified drinking water matching bottle volume",
            "difficulty": "easy",
        },
        {
            "name": "Bleach Disinfectant Solution",
            "category": "cleaning",
            "ingredients": [
                {"name": "unscented household bleach (6-8.25% sodium hypochlorite)", "quantity": "1 tablespoon"},
                {"name": "water", "quantity": "1 gallon"},
            ],
            "procedure": [
                "Ensure bleach is unscented and not expired.",
                "Measure 1 tablespoon (15ml) of bleach.",
                "Add to 1 gallon of clean water.",
                "Mix well.",
                "For surface disinfection: apply and let sit for 10 minutes, then air dry.",
                "For water purification: use 8 drops per gallon, wait 30 minutes.",
                "Make fresh daily - solution loses potency over time.",
            ],
            "safety_notes": "Never mix bleach with ammonia or acids. Ventilate area. Wear gloves. Keep away from children.",
            "yield": "1 gallon of disinfectant solution",
            "difficulty": "easy",
        },
        {
            "name": "Activated Charcoal Water Filter",
            "category": "water_treatment",
            "ingredients": [
                {"name": "charcoal (hardwood)", "quantity": "2-3 lbs crushed"},
                {"name": "sand (clean, coarse)", "quantity": "2-3 lbs"},
                {"name": "gravel (clean)", "quantity": "2-3 lbs"},
                {"name": "large container or PVC pipe", "quantity": "1"},
                {"name": "cloth or screen", "quantity": "for bottom filter"},
            ],
            "procedure": [
                "Crush charcoal into small pieces (pea-sized or smaller).",
                "Drill drainage hole in bottom of container.",
                "Place cloth/screen over hole.",
                "Layer 1 (bottom): 3 inches of gravel.",
                "Layer 2: 3 inches of coarse sand.",
                "Layer 3: 6 inches of crushed charcoal.",
                "Layer 4 (top): 3 inches of sand.",
                "Flush filter with clean water before first use.",
                "Pour water through top and collect filtered water from bottom.",
            ],
            "safety_notes": "This filter removes sediment, odors, and some chemicals but does NOT kill bacteria. Boil or treat filtered water before drinking.",
            "yield": "Continuous filtered water - replace charcoal every 2-3 months",
            "difficulty": "easy",
        },
        {
            "name": "Herbal Insect Repellent",
            "category": "personal_care",
            "ingredients": [
                {"name": "citronella leaves or lemongrass", "quantity": "1 cup chopped"},
                {"name": "carrier oil (olive, coconut)", "quantity": "1 cup"},
                {"name": "beeswax (optional, for balm)", "quantity": "2 tablespoons"},
            ],
            "procedure": [
                "Bruise/crush citronella or lemongrass leaves.",
                "Place in jar and cover with carrier oil.",
                "Seal and place in sunny window for 2 weeks, shaking daily.",
                "Strain through cheesecloth into clean container.",
                "For liquid repellent: use oil directly on skin.",
                "For balm: melt beeswax, mix with infused oil, pour into tins.",
                "Reapply every 1-2 hours for effectiveness.",
            ],
            "safety_notes": "Test on small skin area first for allergic reaction. Less effective than commercial DEET products. Avoid eyes.",
            "yield": "Approximately 1 cup of repellent oil",
            "difficulty": "easy",
        },
        {
            "name": "Natural Plant Dye",
            "category": "textile",
            "ingredients": [
                {"name": "plant material (onion skins, berries, walnut hulls)", "quantity": "1 lb"},
                {"name": "water", "quantity": "2 gallons"},
                {"name": "alum (potassium aluminum sulfate)", "quantity": "4 tablespoons"},
                {"name": "fabric or yarn (natural fibers only)", "quantity": "as needed"},
            ],
            "procedure": [
                "Mordant fabric: dissolve alum in warm water, soak fabric for 1 hour.",
                "Chop plant material and place in large pot with water.",
                "Simmer (do not boil) for 1-2 hours until color is extracted.",
                "Strain out plant material.",
                "Add mordanted fabric to dye bath.",
                "Simmer for 1-2 hours, stirring occasionally.",
                "Remove fabric and rinse in cool water until water runs clear.",
                "Hang to dry out of direct sunlight.",
            ],
            "safety_notes": "Use dedicated dye pots - do not use for food. Some mordants are toxic. Natural dyes may fade over time.",
            "yield": "Dyed fabric - color depends on plant source",
            "difficulty": "medium",
        },
    ]

    for recipe in recipes:
        execute(
            """INSERT INTO chemistry_recipes (name, category, ingredients, procedure, safety_notes, yield, difficulty)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (
                recipe["name"],
                recipe["category"],
                json.dumps(recipe["ingredients"]),
                json.dumps(recipe["procedure"]),
                recipe["safety_notes"],
                recipe["yield"],
                recipe["difficulty"],
            ),
        )
