"""Natural medicine seed data - survival-relevant herbal remedies."""

NATURAL_MEDICINES = [
    {
        "name": "Yarrow",
        "common_names": "Achillea millefolium, Soldier's woundwort, Nosebleed plant",
        "uses": "Wound healing, stop bleeding, fever reduction, digestive aid, anti-inflammatory",
        "preparation": "Poultice: crush fresh leaves and apply to wounds. Tea: steep 1-2 tsp dried herb in hot water for 10 min. Tincture: 1:5 ratio in 40% alcohol.",
        "dosage": "Tea: 1 cup 3x daily. Tincture: 2-4 mL 3x daily. Poultice: apply as needed.",
        "contraindications": "Pregnancy (uterine stimulant), allergy to Asteraceae family, children under 6",
        "drug_interactions": "May increase effect of anticoagulants (warfarin), antihypertensives, sedatives",
        "habitat": "Meadows, roadsides, disturbed ground. Found throughout temperate regions worldwide.",
        "identification": "Feathery, fern-like leaves. Flat-topped clusters of small white or pink flowers. Strong aromatic scent. Height 30-60 cm.",
        "notes": "One of the most versatile survival medicinal plants. Named after Achilles who reportedly used it to treat soldiers' wounds.",
    },
    {
        "name": "Willow Bark",
        "common_names": "Salix alba, White willow, Nature's aspirin",
        "uses": "Pain relief, fever reduction, anti-inflammatory, headache, back pain, osteoarthritis",
        "preparation": "Decoction: simmer 1-2 tsp dried bark in water for 10-15 min. Chew fresh inner bark for quick pain relief.",
        "dosage": "Decoction: 1 cup up to 4x daily (equivalent to ~240mg salicin/day). Chew small piece of bark as needed.",
        "contraindications": "Aspirin allergy, children under 16 (Reye's syndrome risk), peptic ulcer, bleeding disorders, pregnancy",
        "drug_interactions": "Increases effect of anticoagulants, NSAIDs. May interact with methotrexate, phenytoin.",
        "habitat": "Near water sources - rivers, streams, lakes. Widely distributed in temperate and arctic zones.",
        "identification": "Deciduous tree with long narrow leaves, silvery underneath. Flexible drooping branches. Gray furrowed bark.",
        "notes": "Contains salicin, the natural precursor to aspirin (acetylsalicylic acid). Slower onset but longer duration than aspirin.",
    },
    {
        "name": "Echinacea",
        "common_names": "Echinacea purpurea, Purple coneflower, Black sampson",
        "uses": "Immune support, upper respiratory infections, wound healing, urinary tract infections",
        "preparation": "Tea: steep 1-2 tsp dried herb/root for 15 min. Tincture: 1:5 in 45% alcohol. Poultice for wounds.",
        "dosage": "Tea: 1 cup 3x daily at onset of symptoms. Tincture: 2.5 mL 3x daily. Use for 7-10 days maximum.",
        "contraindications": "Autoimmune diseases, progressive systemic diseases (TB, MS, HIV), allergy to Asteraceae",
        "drug_interactions": "May reduce effectiveness of immunosuppressants. Possible interaction with CYP3A4 substrates.",
        "habitat": "Open prairies and woodlands of central and eastern North America. Cultivated worldwide.",
        "identification": "Purple-pink daisy-like flowers with spiny orange-brown center cone. Rough hairy stems. Lance-shaped leaves.",
        "notes": "Most effective when taken at first sign of infection. Do not use continuously; cycle 2 weeks on, 1 week off.",
    },
    {
        "name": "Plantain",
        "common_names": "Plantago major, Broadleaf plantain, White man's footprint",
        "uses": "Insect bites, stings, minor wounds, burns, rashes, cough, digestive issues",
        "preparation": "Poultice: chew or crush fresh leaves, apply directly. Tea: steep 1 tbsp dried leaves in hot water for 10 min.",
        "dosage": "Poultice: apply as needed, change every few hours. Tea: 1 cup 3x daily.",
        "contraindications": "Generally very safe. Rare allergic reactions possible.",
        "drug_interactions": "May reduce absorption of some medications if taken simultaneously (high fiber content).",
        "habitat": "Ubiquitous weed found in lawns, paths, disturbed areas worldwide. One of the most accessible medicinal plants.",
        "identification": "Broad oval leaves in basal rosette with prominent parallel veins. Green flower spikes on leafless stems.",
        "notes": "Essential wilderness first-aid plant. Available almost everywhere. Children can safely use it for bee stings and scrapes.",
    },
    {
        "name": "Elderberry",
        "common_names": "Sambucus nigra, Black elder, Elder",
        "uses": "Cold and flu treatment, immune support, antioxidant, fever reduction",
        "preparation": "Syrup: cook berries with honey and water. Tea: steep dried flowers or berries. MUST be cooked - raw berries are toxic.",
        "dosage": "Syrup: 1 tbsp 4x daily for adults, 1 tsp for children. Tea: 1 cup 3x daily.",
        "contraindications": "Raw berries, bark, and leaves are TOXIC (contain cyanogenic glycosides). Autoimmune conditions.",
        "drug_interactions": "May increase effect of immunosuppressants (theoretical). May interact with diabetes medications.",
        "habitat": "Hedgerows, woodland edges, waste ground. Common in Europe and North America.",
        "identification": "Shrub/small tree with compound leaves (5-7 leaflets). Flat-topped clusters of cream flowers. Drooping clusters of dark purple-black berries.",
        "notes": "WARNING: All parts except cooked berries and flowers are toxic. Never eat raw berries. Cook thoroughly.",
    },
    {
        "name": "Chamomile",
        "common_names": "Matricaria chamomilla, German chamomile, Wild chamomile",
        "uses": "Anxiety, insomnia, digestive complaints, skin inflammation, wound healing, colic in children",
        "preparation": "Tea: steep 2-3 tsp dried flowers in hot water for 5-10 min (cover to retain oils). Compress: soak cloth in strong tea.",
        "dosage": "Tea: 1 cup 3-4x daily. For sleep: 1 cup 30 min before bed.",
        "contraindications": "Allergy to Asteraceae family. Use caution in pregnancy (traditional uterine stimulant).",
        "drug_interactions": "May increase effect of anticoagulants and sedatives. Possible interaction with CYP substrates.",
        "habitat": "Fields, roadsides, cultivated ground. Native to Europe and western Asia.",
        "identification": "Small daisy-like flowers with white petals and yellow dome center. Feathery leaves. Apple-like fragrance when crushed.",
        "notes": "One of the safest medicinal herbs. Suitable for children and elderly. The tea is the most common preparation.",
    },
    {
        "name": "Garlic",
        "common_names": "Allium sativum, Stinking rose",
        "uses": "Antimicrobial, immune support, cardiovascular health, antifungal, antiparasitic, ear infections",
        "preparation": "Crush and let sit 10 min to activate allicin. Eat raw for maximum benefit. Oil infusion for ear drops.",
        "dosage": "Raw: 1-2 cloves 2-3x daily. Ear drops: warm garlic oil, 2-3 drops. Poultice: crushed garlic on skin (protect with oil first).",
        "contraindications": "Bleeding disorders, pre-surgery (stop 7 days before). Direct skin application can cause burns.",
        "drug_interactions": "Increases effect of anticoagulants. May reduce effectiveness of saquinavir and some HIV drugs.",
        "habitat": "Cultivated worldwide. Easy to grow in most climates.",
        "identification": "Bulb with papery white skin containing cloves. Flat, long leaves. Tall flower stalk with round cluster.",
        "notes": "Crushing and waiting 10 minutes before cooking preserves allicin content. One of the most potent natural antimicrobials.",
    },
    {
        "name": "Ginger",
        "common_names": "Zingiber officinale",
        "uses": "Nausea, motion sickness, digestive aid, anti-inflammatory, circulation, cold and flu",
        "preparation": "Tea: slice fresh root, steep in hot water 10-15 min. Chew raw for nausea. Poultice for joint pain.",
        "dosage": "Tea: 1 cup as needed. Fresh: 1-2 g daily. For nausea: chew small piece or sip tea.",
        "contraindications": "Gallstones, high-dose use in pregnancy (low-dose OK for morning sickness)",
        "drug_interactions": "May increase effect of anticoagulants. May interact with diabetes medications (hypoglycemia).",
        "habitat": "Tropical and subtropical regions. Grows well in containers indoors.",
        "identification": "Knobbly tan rhizome with pale yellow interior. Reed-like stems with narrow leaves.",
        "notes": "Excellent for nausea of all types including pregnancy-related. Can be dried and stored long-term.",
    },
    {
        "name": "Turmeric",
        "common_names": "Curcuma longa, Indian saffron",
        "uses": "Anti-inflammatory, antioxidant, digestive aid, wound healing, joint pain",
        "preparation": "Golden paste: mix powder with black pepper and oil for absorption. Tea: simmer root/powder in water.",
        "dosage": "Powder: 1-3 g daily with fat and black pepper. Tea: 1 cup 2-3x daily.",
        "contraindications": "Gallstones, bile duct obstruction, pregnancy (high doses), pre-surgery",
        "drug_interactions": "May increase effect of anticoagulants and antiplatelet drugs. May interact with diabetes medications.",
        "habitat": "Tropical regions of South Asia. Requires warm humid climate.",
        "identification": "Bright orange-yellow rhizome. Large lily-like leaves. Related to ginger.",
        "notes": "Bioavailability greatly increased by black pepper (piperine) and fat. Very low bioavailability alone.",
    },
    {
        "name": "Aloe Vera",
        "common_names": "Aloe barbadensis, Burn plant, Medicine plant",
        "uses": "Burns, sunburn, wound healing, skin conditions, digestive aid (gel only)",
        "preparation": "Topical: split leaf and apply gel directly to burns/wounds. Internal: blend inner gel with water (remove latex layer).",
        "dosage": "Topical: apply as needed. Internal gel: 1-2 tbsp daily.",
        "contraindications": "Aloe latex is a strong laxative - do not ingest. Pregnancy. Internal use in children.",
        "drug_interactions": "Aloe latex may interact with digoxin, diuretics, diabetes medications, laxatives.",
        "habitat": "Arid and semi-arid regions. Excellent houseplant and container plant.",
        "identification": "Succulent with thick fleshy leaves in rosette pattern. Leaves have small teeth along margins. Yellow-green gel inside.",
        "notes": "Distinguish between inner GEL (safe) and yellow LATEX layer (strong laxative, potentially toxic). Always remove latex.",
    },
    {
        "name": "Peppermint",
        "common_names": "Mentha piperita, Mint",
        "uses": "Digestive aid, nausea, headache, congestion, muscle pain, IBS symptoms",
        "preparation": "Tea: steep fresh or dried leaves in hot water 5-10 min. Oil: dilute for topical use. Steam inhalation for congestion.",
        "dosage": "Tea: 1 cup after meals or as needed. Oil: 1-2 drops diluted in carrier oil for topical application.",
        "contraindications": "GERD (may worsen reflux), hiatal hernia, children under 2 (menthol), gallstones",
        "drug_interactions": "May increase levels of CYP3A4 substrates. May interact with cyclosporine.",
        "habitat": "Moist areas, near water. Extremely easy to grow; can be invasive. Grows in containers.",
        "identification": "Square stems, opposite aromatic leaves with serrated edges. Purple flower spikes. Strong minty smell.",
        "notes": "Invasive grower - plant in containers. Both dried and fresh leaves are effective. One of the most pleasant medicinal teas.",
    },
    {
        "name": "Calendula",
        "common_names": "Calendula officinalis, Pot marigold, Marigold",
        "uses": "Wound healing, skin inflammation, burns, rashes, antifungal, antibacterial",
        "preparation": "Salve: infuse dried flowers in oil for 4-6 weeks, add beeswax. Tea: steep 2 tsp flowers in hot water. Compress: strong tea applied to wounds.",
        "dosage": "Topical: apply salve or compress 2-3x daily. Tea: 1 cup 3x daily for internal use.",
        "contraindications": "Allergy to Asteraceae family. Pregnancy (may stimulate uterus).",
        "drug_interactions": "May increase sedative effects. Theoretical interaction with diabetes medications.",
        "habitat": "Gardens, waste ground. Easy to grow from seed in most climates.",
        "identification": "Bright orange or yellow daisy-like flowers. Sticky, aromatic leaves. Grows 30-60 cm tall.",
        "notes": "Excellent wound-healing herb. Can be dried and stored for years. Very easy to grow and self-seeds readily.",
    },
    {
        "name": "Comfrey",
        "common_names": "Symphytum officinale, Knitbone, Boneset",
        "uses": "Fractures, sprains, bruises, wound healing (EXTERNAL USE ONLY)",
        "preparation": "Poultice: mash fresh leaves or reconstitute dried root, apply to injury. Oil: infuse in carrier oil.",
        "dosage": "External only: apply poultice or salve 2-3x daily for up to 10 days.",
        "contraindications": "NEVER take internally (hepatotoxic pyrrolizidine alkaloids). Do not use on deep or infected wounds. Pregnancy.",
        "drug_interactions": "None significant for external use.",
        "habitat": "Damp meadows, riverbanks, ditches. Common in temperate regions.",
        "identification": "Large hairy leaves. Drooping bell-shaped purple, pink, or white flowers. Thick black taproot.",
        "notes": "WARNING: External use only. Contains pyrrolizidine alkaloids that are toxic to the liver. Do not apply to broken skin.",
    },
    {
        "name": "Valerian",
        "common_names": "Valeriana officinalis, Garden valerian, All-heal",
        "uses": "Insomnia, anxiety, muscle relaxation, stress relief",
        "preparation": "Tea: steep 1 tsp dried root in hot water 10-15 min. Tincture: 1:5 in 60% alcohol. Cold infusion preserves more compounds.",
        "dosage": "Tea: 1 cup before bed. Tincture: 2-5 mL before bed. Allow 2-4 weeks for full effect.",
        "contraindications": "Pregnancy, children under 3. May cause paradoxical stimulation in some individuals.",
        "drug_interactions": "May increase effects of sedatives, benzodiazepines, and alcohol. May interact with CYP3A4 substrates.",
        "habitat": "Damp grasslands, riverbanks, woodland edges. Widely cultivated.",
        "identification": "Tall plant (up to 1.5 m) with pinnate leaves. Clusters of small white-pink flowers. Root has distinctive strong odor.",
        "notes": "The root is the medicinal part. Strong unpleasant smell is normal. Cats are attracted to it (similar to catnip).",
    },
    {
        "name": "Mullein",
        "common_names": "Verbascum thapsus, Great mullein, Velvet plant",
        "uses": "Respiratory conditions, cough, bronchitis, ear infections, anti-inflammatory",
        "preparation": "Tea: steep 1-2 tsp dried leaves/flowers 10-15 min, STRAIN through fine cloth. Ear oil: infuse flowers in olive oil.",
        "dosage": "Tea: 1 cup 3-4x daily. Ear oil: 2-3 warm drops in affected ear.",
        "contraindications": "Must strain tea through fine cloth to remove irritating hairs. Pregnancy (insufficient data).",
        "drug_interactions": "No significant known interactions.",
        "habitat": "Disturbed ground, roadsides, dry fields. Common weed in many regions.",
        "identification": "Large fuzzy gray-green basal rosette first year. Tall flower spike (up to 2 m) with yellow flowers second year.",
        "notes": "Biennial - rosette first year, flower stalk second. The soft leaves were historically used as wound dressings and toilet paper.",
    },
]


def seed_natural_medicines(execute_fn, query_fn) -> None:
    """Seed the natural medicines table."""
    existing = query_fn("SELECT COUNT(*) as count FROM natural_medicines")
    if existing[0]["count"] > 0:
        return

    for nm in NATURAL_MEDICINES:
        execute_fn(
            """INSERT INTO natural_medicines
               (name, common_names, uses, preparation, dosage, contraindications,
                drug_interactions, habitat, identification, notes)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (nm["name"], nm["common_names"], nm["uses"], nm["preparation"],
             nm["dosage"], nm["contraindications"], nm["drug_interactions"],
             nm["habitat"], nm["identification"], nm["notes"]),
        )
